### ISSUE TITLE
Problems with Ember-CLI 2.14.0 

### ISSUE THREAD

**Issue by matixmatix** [algonauti/ember-cable#22]
After I upgraded my project from 2.12.0 to 2.14.0, I got the following error:

```
[20:43:35] jurgen:formaviva-web git:(master*) $ ember s
Livereload server on http://localhost:49153
'instrument' is imported from external module 'ember-data/-debug' but never used
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger: `addon/` trees] failed with:
TypeError: ember-cable/core/connection.js: pluginList.indexOf is not a function
    at Parser.loadPlugins (/Users/jurgen/development/formaviva-web/node_modules/babylon/lib/index.js:1620:20)
    at new Parser (/Users/jurgen/development/formaviva-web/node_modules/babylon/lib/index.js:1573:27)
    at Object.parse (/Users/jurgen/development/formaviva-web/node_modules/babylon/lib/index.js:7246:10)
    at Object.exports.default (/Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at /Users/jurgen/development/formaviva-web/node_modules/ember-cable/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
```

**Comment by safeforge** [comment]
seems to be as a outdated issue. I'm going to close
